// flow-typed signature: 109e6fc323e269b3692197b6e81b323b
// flow-typed version: <<STUB>>/postcss-inline-rtl_v^0.9.8/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-inline-rtl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-inline-rtl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-inline-rtl/propsToAlwaysConvert' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-inline-rtl/index' {
  declare module.exports: $Exports<'postcss-inline-rtl'>;
}
declare module 'postcss-inline-rtl/index.js' {
  declare module.exports: $Exports<'postcss-inline-rtl'>;
}
declare module 'postcss-inline-rtl/propsToAlwaysConvert.js' {
  declare module.exports: $Exports<'postcss-inline-rtl/propsToAlwaysConvert'>;
}
