// flow-typed signature: a8c8ee81ea1e14b3a4ee8dbd7d4cdf0f
// flow-typed version: <<STUB>>/react-intl-universal_v^1.11.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl-universal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl-universal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl-universal/dist/intl-universal' {
  declare module.exports: any;
}

declare module 'react-intl-universal/dist/intl-universal.min' {
  declare module.exports: any;
}

declare module 'react-intl-universal/dist/react-intl-universal' {
  declare module.exports: any;
}

declare module 'react-intl-universal/dist/test' {
  declare module.exports: any;
}

declare module 'react-intl-universal/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl-universal/dist/intl-universal.js' {
  declare module.exports: $Exports<'react-intl-universal/dist/intl-universal'>;
}
declare module 'react-intl-universal/dist/intl-universal.min.js' {
  declare module.exports: $Exports<'react-intl-universal/dist/intl-universal.min'>;
}
declare module 'react-intl-universal/dist/react-intl-universal.js' {
  declare module.exports: $Exports<'react-intl-universal/dist/react-intl-universal'>;
}
declare module 'react-intl-universal/dist/test.js' {
  declare module.exports: $Exports<'react-intl-universal/dist/test'>;
}
declare module 'react-intl-universal/lib/index.js' {
  declare module.exports: $Exports<'react-intl-universal/lib/index'>;
}
